### ISSUE TITLE
not able to fetch activities with cursor (nonetype)

### ISSUE THREAD

**Issue by cellsheet** [soundcloud/soundcloud-python#75]
I'm attempting to traverse through my activities using `client.get('/me/activities?cursor=<cursor>')`, which results in:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/soundcloud/client.py", line 133, in _request
    return wrapped_resource(make_request(method, url, kwargs))
  File "/usr/lib/python3.5/site-packages/soundcloud/resource.py", line 69, in wrapped_resource
    result.collection = ResourceList(result.collection)
  File "/usr/lib/python3.5/site-packages/soundcloud/resource.py", line 46, in __init__
    data = [Resource(resource) for resource in resources]
  File "/usr/lib/python3.5/site-packages/soundcloud/resource.py", line 46, in <listcomp>
    data = [Resource(resource) for resource in resources]
  File "/usr/lib/python3.5/site-packages/soundcloud/resource.py", line 20, in __init__
    self.origin = Resource(self.origin)
  File "/usr/lib/python3.5/site-packages/soundcloud/resource.py", line 19, in __init__
    if hasattr(self, 'origin'):
  File "/usr/lib/python3.5/site-packages/soundcloud/resource.py", line 32, in __getattr__
    if name in self.obj:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by brocef** [comment]
Not sure if anyone else also sees this error, but I was getting it for a while until I removed the named limit argument from my call to client.get().
`tracks = client.get('/me/activities', limit=300)`
to
`tracks = client.get('/me/activities')`
And now it works. Not sure why.
