### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by Rafff** [soundcloud/soundcloud-python#79]
Hi,

A problem showed up recently, causing this error to happen : 

> SSLError: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

This happen in a program that have been working for a long time before, it broke a few weeks ago.

I can reproduce using this :

Dependencies :
`argparse==1.2.1
fudge==1.1.0
requests==2.13.0
simplejson==3.10.0
six==1.10.0
soundcloud==0.5.0
wsgiref==0.1.2`

This code :
```python
import soundcloud
client = soundcloud.Client(client_id=YOUR_SOUNDCLOUD_CLIENT_ID)
track = client.get('/resolve', url='https://soundcloud.com/effiscienz/union-blak-street-english')
```
Throws an Exception, here is the traceback :
```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    track = client.get('/resolve', url='https://soundcloud.com/effiscienz/union-blak-street-english')
  File "/home/niland/workspace/tmp/venv/local/lib/python2.7/site-packages/soundcloud/client.py", line 133, in _request
    return wrapped_resource(make_request(method, url, kwargs))
  File "/home/niland/workspace/tmp/venv/local/lib/python2.7/site-packages/soundcloud/request.py", line 136, in make_request
    result = request_func(url_qs, **kwargs)
  File "/home/niland/workspace/tmp/venv/local/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/home/niland/workspace/tmp/venv/local/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/niland/workspace/tmp/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/niland/workspace/tmp/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/niland/workspace/tmp/venv/local/lib/python2.7/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
```

I tried to install things I've read googling, such as requests[security] or pyopenssl + ndg-httpsclient + pyasn1,  nothing made this worked.

Does anyone has a solution to fix the client ?

Thanks.

**Comment by Rafff** [comment]
It seems that the problem exists in version 2.7.6 (default ubuntu version).
upgrading to 2.7.9 might fix it, as mentionned here : http://stackoverflow.com/questions/35405092/sslerror-sslv3-alert-handshake-failure

**Comment by slaponicus** [comment]
Hi @Rafff,

Did you ever get this working? I'm experiencing the same issue with Python 3.4 with pretty much the same code and dependencies installed. Also happening for an app that had been working for about a year.

**Comment by Rafff** [comment]
My problem was happening with python 2.7. On my end, it has been solved
updating to python 2.9

**Comment by slaponicus** [comment]
Thanks for your reply! Looks like this is a bigger issue for me wherein Django decided to use the system python instead of the virtualenv python...

**Comment by SaulFemm** [comment]
Is there another solution if I have to stay on 2.7.2?
